// <auto-generated />
using Infrastructure.Skinet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Skinet.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20240615180721_Begin")]
    partial class Begin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Skinet.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductBrandId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is a description for product 1",
                            Name = "Product 1",
                            Picture = "images/products/sb-ang1.png",
                            Price = 0.169889285825772m,
                            ProductBrandId = 1,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is a description for product 2",
                            Name = "Product 2",
                            Picture = "images/products/sb-ang2.png",
                            Price = 0.477062243023867m,
                            ProductBrandId = 2,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is a description for product 3",
                            Name = "Product 3",
                            Picture = "images/products/sb-core1.png",
                            Price = 0.683599240284728m,
                            ProductBrandId = 3,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is a description for product 4",
                            Name = "Product 4",
                            Picture = "images/products/sb-core2.png",
                            Price = 0.558487098171239m,
                            ProductBrandId = 4,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is a description for product 5",
                            Name = "Product 5",
                            Picture = "images/products/sb-react1.png",
                            Price = 0.411972244496337m,
                            ProductBrandId = 5,
                            ProductTypeId = 5
                        });
                });

            modelBuilder.Entity("Domain.Skinet.Entities.ProductBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product Brand 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product Brand 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product Brand 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product Brand 3"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product Brand 4"
                        });
                });

            modelBuilder.Entity("Domain.Skinet.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product Type 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product Type 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product Type 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product Type 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product Type 5"
                        });
                });

            modelBuilder.Entity("Domain.Skinet.Entities.Product", b =>
                {
                    b.HasOne("Domain.Skinet.Entities.ProductBrand", "ProductBrand")
                        .WithMany()
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Skinet.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
