services:
  sql-database:
     container_name: database-skinet
     image: mcr.microsoft.com/mssql/server:2022-latest
     networks:
       - skinet-network
     ports:
      - "1433:1433"
     environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: <YourStrong@Passw0rd>
     volumes:
       - sql-server-data:/var/opt/mssql/data
     restart: always
     user: root
  
  # memory-db:
  #   container_name: redis_skinet
  #   image: redis:alpine3.19
  #   volumes: 
  #     - redis-db-data:/var/opt/redis/data
  #   networks:
  #     - skinet_network
  
  # broker:
  #   container_name: rabbitmq_skinet
  #   image: rabbitmq:3.9.29-management
  #   networks:
  #     - skinet_network

volumes:
  sql-server-data:  
  # redis-db-data:


networks:
  skinet-network:
    name: skinet-network
    driver: bridge
    external: false

