# Development composer

# Notes:

# - This composer only contain the necessary services for development, for production environment use docker-compose.yml as reference.

# - up and down scripts execute the stack creation and deletion, also purging the volumes, they are written to be use during development tests, if you need to persist data remove the "--volumes" parameter from the down.ps1 script.

# - to run the scripts on Unix systems just rename them to up.sh/down.sh and give chmod execution permissions, or install powershell for linux. (linux-only: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux)

services:
  postgres:
    container_name: database-skinet
    image: postgres:12.19-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skinet
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - skinet-network
    restart: unless-stopped

  redis:
    container_name: redis-skinet
    image: redis:alpine3.19
    volumes: 
      - memory-database-persistence:/var/opt/redis/data
    networks:
      - skinet-network
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq-skinet
    image: rabbitmq:3.9.29-management
    networks:
      - skinet-network
    hostname: "rabbitmq-skinet"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  postgres:
    name: postgres-skinet
  redis:
    name: redis-skinet

networks:
  skinet-network:
    name: skinet-network
    driver: bridge
    external: false
