# Production composer

services:
  application-skinet:
    container_name: application-skinet
    image: vinimorgado/skinet-api:latest
    networks:
      - skinet-network
    ports:
      - "10401:10401"
    depends_on: 
      postgres-skinet:
        condition: service_started

  postgres-skinet:
    container_name: postgres-skinet
    image: postgres:12.19-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skinet
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - skinet-network
    restart: unless-stopped

  seq-skinet:
    container_name: seq-skinet
    image: datalust/seq:latest
    networks:
      - skinet-network
    restart: unless-stopped
    volumes:
    - seq:/data
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "10402:80"
      # - "9110:5341"

volumes:
  postgres:
    name: postgres-skinet
  seq:
    name: seq-skinet

networks:
  skinet-network:
    name: skinet-network
    driver: bridge
    external: false
